export const products = [ 
    {
        productName: "Pantalón Jogging  Gris S M",
        price: 12000,
        Id: 1,
        category: "Pantalones",
        description: "Pantalon de Joggin Hombre talles S y M",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680492/react-adrian/id1_h2ddpp.jpg" ,
        stock: 70,
    },
    {
        productName: "Pantalón Jogging Negro S M",
        price: 12000,
        Id: 2,
        category: "Pantalones",
        description: "Pantalón de Jogging talles S y M",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680492/react-adrian/id2_ne1xom.jpg",
        stock: 8,
    },
    {
        productName: "Pantalón jean M L",
        price: 14900,
        Id: 3,
        category: "Pantalones",
        description: "Pantalón Jean Hombre Talles M y L",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680492/react-adrian/id3_lmx8kk.jpg" ,
        stock: 15,
    },
    {
        productName: "Pantalón jean s xs",
        price: 14900,
        Id: 4,
        category: "Pantalones",
        description: "Pantalón Jean Hombre Talles X y XS",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680493/react-adrian/id4_o18gnr.jpg" ,
        stock: 10,
    },
    {
        productName: "Remera Básica Blanca",
        price: 5000,
        Id: 5,
        category: "Remeras",
        description: "Remera básica Blanca - Todos los talles",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680492/react-adrian/id_5_qvh1ps.jpg" ,
        stock: 6,
    },
    {
        productName: "Remera básica Negra - Todos los talles",
        price: 5000,
        Id: 6,
        category: "Remeras",
        description: "Remera básica negra - Todos los talles",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680493/react-adrian/id6_apbmys.jpg" ,
        stock: 5,
    },
    {
        productName: "Remera básica azul",
        price: 5000,
        Id: 7,
        category: "ArRemeras",
        description: "Remera básica Azul - Todos los talles",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680493/react-adrian/id7_fathcq.jpg",
        stock: 2,
    },
    {
        productName: "Calzado deportivo Hombre",
        price: 2500,
        Id: 8,
        category: "Calzado",
        description: "Calzado deportivo Hombre - Todos los números",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680493/react-adrian/id8_hwfjle.jpg",
        stock: 5,
    },
    {
        productName: "Calzado deportivo Mujer",
        price: 25000,
        Id: 9,
        category: "Calzado",
        description: "Calzado deportivo Mujwer - Todos los números",
        img: "https://res.cloudinary.com/dsasb1zeq/image/upload/v1670680493/react-adrian/id9_q7jwkq.jpg" ,
        stock: 20,
    }
]